name: Compile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu-x86_64:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
  
    - name: Install environment
      shell: bash
      run: sudo apt-get install -y git wget rpm rpm2cpio cpio make build-essential binutils m4

    - name: Cache build files
      id: cache-dep
      uses: actions/cache@v3
      with:
        path: |
          deps
          ~/.ccache
        key: ${{github.job}}-${{github.ref}}-${{github.sha}}
        restore-keys: |
          ${{github.job}}-${{github.ref}}-
          ${{github.job}}-
  
    - name: Build project
      shell: bash
      run: | 
        bash build.sh init
        bash build.sh debug
        cd build_debug && make -j4
        
